name: Performance

on:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  ubuntu-gcc-build-perf-stats:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/learning-process/ppc-ubuntu:1.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Setup environment
        run: |
          python3 -m pip install -r requirements.txt --break-system-packages --ignore-installed
      - name: Configure perf build
        run: >
          cmake -S . -B build -G Ninja
          -D CMAKE_BUILD_TYPE=Release
          -D USE_FUNC_TESTS=OFF
          -D USE_PERF_TESTS=ON
        env:
          CC: gcc-14
          CXX: g++-14
      - name: Build perf tests
        run: cmake --build build --target ppc_perf_tests --parallel -- --quiet
        env:
          CC: gcc-14
          CXX: g++-14
      - name: Run perf tests
        run: |
          bash -e scripts/generate_perf_results.sh
        env:
          PPC_NUM_PROC: 2
          PPC_NUM_THREADS: 2
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      - name: Archive results
        working-directory: build
        run: zip -r ../perf-stat.zip perf_stat_dir
      - name: Upload results
        uses: actions/upload-artifact@v6
        with:
          name: perf-stat
          path: perf-stat.zip
